### ISSUE TITLE
How can I run npm test?

### ISSUE THREAD

**Issue by haruelrovix** [Meyjan/AskSteveNode#1]
Hi @Meyjan 👋🏻 

I'm Havit from AdaKerja. Thanks for the submission. 

Small question, How can I run the `npm test` successfully?

```
➜  AskSteveNode git:(main) npm test

> jest --silent

 FAIL  test/webhookHelper.test.js
  ● Test suite failed to run

    MongooseError: The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()` or `mongoose.createConnection()` is a string.

      3 | const poolSize = process.env.DB_POOL_SIZE;
      4 |
    > 5 | const db = mongoose.createConnection(dbUrl, { poolSize: poolSize, useNewUrlParser: true, useUnifiedTopology: true })
        |                     ^
      6 |
      7 | module.exports = {
      8 |     conn: () => {

      at NativeConnection.Object.<anonymous>.Connection.openUri (node_modules/mongoose/lib/connection.js:680:11)
      at Mongoose.createConnection (node_modules/mongoose/lib/index.js:285:17)
      at Object.<anonymous> (src/utils/db.js:5:21)
      at Object.<anonymous> (src/helpers/dbHelper.js:1:1)
      at Object.<anonymous> (src/helpers/webhookHelper.js:2:18)
      at Object.<anonymous> (test/webhookHelper.test.js:4:23)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        2.65 s
npm ERR! Test failed.  See above for more details.
```

Thank You.

**Comment by Meyjan** [comment]
Thank you for your reply Mr.@haruelrovix ,

First of all, sorry for the late reply. The cause of that error is the lack of .env file which is not comitted to the github repository because I feel like that file should be kept as a secret. `npm start` can't be run too because it needs the .env file for the link to the database. So, the .env file is sent through the email along with my submission link. As for the .env file that I used, it is as follows:

```
# Basic config
PORT = 8080

# Facebook
FACEBOOK_PAGE_ID = 103274365095233
FACEBOOK_PAGE_APP = 225746785753675
FACEBOOK_PAGE_VERIFY_TOKEN = EAADNUMT5WksBAH7S2huLY4kIZBEfLCSUl7CZBEdf0dfzP8luqUsANcl8i7YgxFKc7Sn4NWRXoZCCMlpiZAYbkiW7ZB5S0ZB46xsTLzCJ6vuwcmDGxd4DI7AiQbTwxLCX0K9FG4IZCX4Dt1rx9KZCqmj9aP4V7XyRCAXbKzLt0n8EBwLbugv40BYm
FACEBOOK_APP_SECRET = 6c3cfbfd19c855b7ef5e2369c639afdb

# Database
DB_URL = 'mongodb+srv://all_db:yrv2zr6g1mE1iMq0@meyjan.eftbp.mongodb.net/simple_messenger?retryWrites=true&w=majority'
DB_POOL_SIZE = 5
USER_COLLECTION = 'users'
MESSAGE_COLLECTION = 'messages'
```

After adding that .env file, the test file can be run and the result is a pass because I did not make any test case about accessing mongodb database.

But there is still an additional error because jest normally doesn't support mongodb even though the initial test works out. I tried solution presented [here](https://jestjs.io/docs/en/mongodb) and [here](https://www.npmjs.com/package/@shelf/jest-mongodb), but didn't work out. Possibly because I tried to implement connection pooling but forgot to close the connection to mongodb.

Best regards,
Jan Meyer Saragih

**Comment by Meyjan** [comment]
Good morning Mr. @haruelrovix ,

I think I have fixed the issue. The issue fixed on [this commit](https://github.com/Meyjan/AskSteveNode/commit/832b82064ad5ad7c2977f99bc75c854da042aea7).

I think the cause of this issue is because of me asking the program to connect to mongodb database when application started. This creates a problem during testing because of testing mongodb using jest requires us to connect to the database in the test environment. The error arises when the test ends and the program tries to close connection with the mongodb database. Then as the solution, I tried to create connection and close the connection during the program runtime.

Best regards,
Jan Meyer Saragih
